const { sequelize, Internship } = require('../models');

const internships = [
  {
    title: 'Backend Engineering Intern',
    company: 'Zoho',
    location: 'Chennai',
    domain: 'Backend Development',
    requiredSkills: ['JavaScript', 'Node.js', 'SQL', 'REST APIs'],
    minimumCGPA: 7.0,
    academicYear: 3,
    stipend: 25000,
    internshipType: 'Onsite',
    description: 'Build and maintain REST APIs for internal productivity products using Node.js and SQL.',
  },
  {
    title: 'Frontend Developer Intern',
    company: 'Razorpay',
    location: 'Bengaluru',
    domain: 'Frontend Development',
    requiredSkills: ['JavaScript', 'React', 'HTML', 'CSS'],
    minimumCGPA: 7.5,
    academicYear: 2,
    stipend: 35000,
    internshipType: 'Hybrid',
    description: 'Create responsive dashboard components for merchant-facing payment workflows.',
  },
  {
    title: 'Data Analyst Intern',
    company: 'Swiggy',
    location: 'Bengaluru',
    domain: 'Data Analytics',
    requiredSkills: ['SQL', 'Excel', 'Python', 'Data Visualization'],
    minimumCGPA: 7.0,
    academicYear: 2,
    stipend: 30000,
    internshipType: 'Hybrid',
    description: 'Analyze restaurant and delivery metrics to support city operations and growth teams.',
  },
  {
    title: 'Machine Learning Intern',
    company: 'Flipkart',
    location: 'Bengaluru',
    domain: 'Machine Learning',
    requiredSkills: ['Python', 'Machine Learning', 'Pandas', 'Scikit-learn'],
    minimumCGPA: 8.0,
    academicYear: 3,
    stipend: 45000,
    internshipType: 'Hybrid',
    description: 'Prototype ranking and recommendation experiments for ecommerce discovery use cases.',
  },
  {
    title: 'Android Developer Intern',
    company: 'Paytm',
    location: 'Noida',
    domain: 'Mobile Development',
    requiredSkills: ['Kotlin', 'Android', 'REST APIs', 'Git'],
    minimumCGPA: 7.0,
    academicYear: 3,
    stipend: 28000,
    internshipType: 'Onsite',
    description: 'Contribute to Android features for wallet, payments, and customer engagement flows.',
  },
  {
    title: 'Product Management Intern',
    company: 'CRED',
    location: 'Bengaluru',
    domain: 'Product Management',
    requiredSkills: ['User Research', 'Analytics', 'Wireframing', 'Communication'],
    minimumCGPA: 7.5,
    academicYear: 3,
    stipend: 40000,
    internshipType: 'Onsite',
    description: 'Support product discovery, requirement writing, and analysis for member experience features.',
  },
  {
    title: 'Cloud Engineering Intern',
    company: 'Freshworks',
    location: 'Chennai',
    domain: 'Cloud Infrastructure',
    requiredSkills: ['Linux', 'AWS', 'Docker', 'Networking'],
    minimumCGPA: 7.2,
    academicYear: 3,
    stipend: 30000,
    internshipType: 'Hybrid',
    description: 'Assist platform teams with cloud automation, monitoring, and deployment reliability tasks.',
  },
  {
    title: 'Cybersecurity Intern',
    company: 'Tata Consultancy Services',
    location: 'Mumbai',
    domain: 'Cybersecurity',
    requiredSkills: ['Networking', 'Linux', 'Security Basics', 'Python'],
    minimumCGPA: 7.0,
    academicYear: 2,
    stipend: 18000,
    internshipType: 'Onsite',
    description: 'Work with security teams on vulnerability tracking, log review, and basic automation.',
  },
  {
    title: 'DevOps Intern',
    company: 'Infosys',
    location: 'Pune',
    domain: 'DevOps',
    requiredSkills: ['Git', 'Docker', 'CI/CD', 'Linux'],
    minimumCGPA: 6.8,
    academicYear: 3,
    stipend: 20000,
    internshipType: 'Hybrid',
    description: 'Help maintain CI pipelines, containerized environments, and deployment documentation.',
  },
  {
    title: 'UI/UX Design Intern',
    company: 'Zomato',
    location: 'Gurugram',
    domain: 'Design',
    requiredSkills: ['Figma', 'User Research', 'Prototyping', 'Design Systems'],
    minimumCGPA: 6.5,
    academicYear: 2,
    stipend: 25000,
    internshipType: 'Hybrid',
    description: 'Design and test user flows for restaurant discovery and consumer app experiences.',
  },
  {
    title: 'QA Automation Intern',
    company: 'BrowserStack',
    location: 'Mumbai',
    domain: 'Quality Assurance',
    requiredSkills: ['JavaScript', 'Testing', 'Selenium', 'Git'],
    minimumCGPA: 7.0,
    academicYear: 2,
    stipend: 32000,
    internshipType: 'Remote',
    description: 'Build automated test cases for browser and device testing workflows.',
  },
  {
    title: 'Business Analyst Intern',
    company: 'Meesho',
    location: 'Bengaluru',
    domain: 'Business Analytics',
    requiredSkills: ['SQL', 'Excel', 'Problem Solving', 'Presentation'],
    minimumCGPA: 7.0,
    academicYear: 2,
    stipend: 28000,
    internshipType: 'Hybrid',
    description: 'Prepare marketplace performance insights for category, supply, and growth teams.',
  },
  {
    title: 'Full Stack Developer Intern',
    company: 'Postman',
    location: 'Remote',
    domain: 'Full Stack Development',
    requiredSkills: ['JavaScript', 'React', 'Node.js', 'MongoDB'],
    minimumCGPA: 7.5,
    academicYear: 3,
    stipend: 50000,
    internshipType: 'Remote',
    description: 'Develop full stack features for API collaboration and developer productivity workflows.',
  },
  {
    title: 'Data Engineering Intern',
    company: 'Dunzo',
    location: 'Bengaluru',
    domain: 'Data Engineering',
    requiredSkills: ['Python', 'SQL', 'ETL', 'Airflow'],
    minimumCGPA: 7.2,
    academicYear: 3,
    stipend: 35000,
    internshipType: 'Hybrid',
    description: 'Support data pipeline development for logistics, catalog, and operations datasets.',
  },
  {
    title: 'AI Research Intern',
    company: 'Sarvam AI',
    location: 'Bengaluru',
    domain: 'Artificial Intelligence',
    requiredSkills: ['Python', 'NLP', 'Deep Learning', 'PyTorch'],
    minimumCGPA: 8.5,
    academicYear: 4,
    stipend: 60000,
    internshipType: 'Onsite',
    description: 'Assist research engineers with experiments for Indian language AI models and evaluation.',
  },
];

const seedInternships = async () => {
  try {
    await sequelize.authenticate();
    await sequelize.sync({ alter: true });

    await Internship.destroy({ truncate: true, restartIdentity: true });
    await Internship.bulkCreate(internships, { validate: true });

    console.log(`Seeded ${internships.length} internships successfully.`);
  } catch (error) {
    console.error('Failed to seed internships:', error);
    process.exitCode = 1;
  } finally {
    await sequelize.close();
  }
};

seedInternships();
